services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: concrete
    ports:
      - '5439:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
  
  account-manager:
    build: .
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: "postgresql://postgres:1234@db:5432/concrete"
    depends_on:
      - db

  payment-manager:
    build:
      context: .
      dockerfile: DockerFile2
    ports:
      - '3003:3002'
    environment:
      DATABASE_URL: "postgresql://postgres:1234@db:5432/concrete"
    depends_on:
      - db


volumes:
  postgres_data:
